
server:
  port: 80
  servlet:
    context-path: /i-home

spring:
  application:
    name: i-Home-app
  # 数据源配置
  datasource:
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/i-home?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      &useSSL=true&serverTimezone=UTC
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: club.bearbear.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

